version: '3'
services: 
  vsce:
    build: 
      context: .
      args: 
        - UID=$UID
        - GID=$GID
    volumes: 
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - .vscode-server:/tmp/.vscode-server
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
  