version: '3'
services: 
  vsce:
    build: 
      context: .
      args: 
        - UID=$UID
        - GID=$GID
    volumes: 
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/test:/tmp/test
    
    
  