version: '3'
services: 
  vsce:
    build: 
      context: .
      args: 
        - UID=$UID
        - GID=$GID
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    volumes: 
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    
    
  